export interface MenuItem {
  id: string;
  name: string;
  category: string;
  ingredients: string[];
  notes?: string;
}

export interface Category {
  id: string;
  name: string;
  emoji: string;
}

export const CATEGORIES: Category[] = [
  { id: 'all', name: 'All Items', emoji: '📋' },
  { id: 'cocktails', name: 'Cocktails', emoji: '🍹' },
  { id: 'appetizers', name: 'Appetizers', emoji: '🥑' },
  { id: 'tacos', name: 'Tacos', emoji: '🌮' },
  { id: 'enchiladas', name: 'Enchiladas', emoji: '🫕' },
  { id: 'burritos', name: 'Burritos', emoji: '🌯' },
  { id: 'quesadillas', name: 'Quesadillas', emoji: '🫔' },
  { id: 'entrees', name: 'Entrees', emoji: '🍽️' },
  { id: 'fajitas', name: 'Fajitas', emoji: '🔥' },
  { id: 'salads', name: 'Salads', emoji: '🥗' },
  { id: 'sandwiches', name: 'Sandwiches', emoji: '🥪' },
  { id: 'brunch', name: 'Brunch', emoji: '🥞' },
  { id: 'veggie', name: 'Veggie', emoji: '🌿' },
  { id: 'desserts', name: 'Desserts', emoji: '🍮' },
];

export const menuItems: MenuItem[] = [
  // ── COCKTAILS ──
  { id: 'frida', name: 'Frida', category: 'cocktails', notes: 'Signature Margarita',
    ingredients: ['Mi Campo Reposado', 'Agave', 'Housemade Fresh Sour', 'Citronage Float', 'Salted Rim'] },
  { id: 'la-flaca', name: 'La Flaca', category: 'cocktails',
    ingredients: ['Mi Campo Blanco', 'Fresh Lime', 'Agave', 'Club Soda', 'Salted Rim'] },
  { id: 'margarita', name: 'Margarita', category: 'cocktails',
    ingredients: ['House Tequila', 'Triple Sec', 'Sour Mix', 'Salted Rim'] },
  { id: 'diablo-pequeno', name: 'Diablo Pequeño', category: 'cocktails',
    ingredients: ['Illegal Mezcal', 'Muddled Jalapeño', 'Agave', 'Fresh Lime', 'Prickly Pear Puree', 'Tajin Rim'] },
  { id: 'paloma', name: 'Paloma', category: 'cocktails',
    ingredients: ['Espolón Blanco', 'Agave', 'Grapefruit Juice', 'Fresh Lime', 'Club Soda', 'Tajin Rim'] },
  { id: 'pale-rider', name: 'Pale Rider', category: 'cocktails',
    ingredients: ['House Whiskey', 'Ginger Beer', 'Angostura Bitters'] },
  { id: 'nopal-burra', name: 'Nopal Burra', category: 'cocktails',
    ingredients: ['Prickly Pear Puree Vodka', 'Fresh Lime', 'Ginger Beer', 'Angostura Bitters'] },
  { id: 'tequila-mockingbird', name: 'Tequila Mockingbird', category: 'cocktails',
    ingredients: ['Espolon Reposado', 'Limoncello', 'Fresh Lemon', 'Agave', 'Angostura Bitters'] },
  { id: 'oaxaca-old-fashioned', name: 'Oaxaca Old Fashioned', category: 'cocktails',
    ingredients: ['Abasolo Oaxaca Whiskey', 'Smoked Glass', 'Agave', 'Orange', 'Angostura Bitters'] },
  { id: 'la-nina-fresa', name: 'La Niña Fresa', category: 'cocktails',
    ingredients: ['Bacardi Silver Rum', 'Fresh Mint', 'Strawberry Puree', 'Agave', 'Fresh Lime', 'Club Soda'] },
  { id: 'michelada', name: 'Michelada', category: 'cocktails',
    ingredients: ['Dos Equis Amber', 'Tomato Juice', 'Spices', 'Citrus', 'Cholula', 'Tajin Rim'] },
  { id: 'pricklyrita', name: 'Pricklyrita', category: 'cocktails',
    ingredients: ['Espolon Reposado', 'Agave', 'Housemade Fresh Sour', 'Prickly Pear Puree', 'Citronage Float', 'Salted Rim'] },
  { id: 'cuba-libre', name: 'Cuba Libre', category: 'cocktails',
    ingredients: ['House Rum', 'Coca Cola', 'Lime Wedge'] },
  { id: 'cucumber-mint-refresher', name: 'Cucumber Mint Refresher', category: 'cocktails',
    ingredients: ["Tito's Vodka", 'Muddled Cucumber', 'Mint', 'Agave', 'Fresh Lime', 'Club Soda'] },

  // ── APPETIZERS ──
  { id: 'tostadas-de-tinga', name: 'Tostadas de Tinga', category: 'appetizers',
    ingredients: ['Three Crispy Fried Tortillas', 'Braised Chicken', 'Onion Chipotle Tomato Sauce', 'Mexican Crema', 'Queso Fresco', 'Lettuce', 'Pickled Onions'] },
  { id: 'tres-amigos', name: 'Tres Amigos', category: 'appetizers',
    ingredients: ['Crispy Tortilla Chips', 'Guacamole', 'Queso Fundido', 'Pico de Gallo'] },
  { id: 'sampler-platter', name: 'Sampler Platter', category: 'appetizers',
    ingredients: ['3 Riblets', '3 Chicken Wings', 'Avocado Eggroll', 'Cheese Quesadilla', 'Sour Cream', 'Avocado-Tomatillo Sauce'] },
  { id: 'pork-belly-burnt-ends', name: 'Pork Belly Burnt Ends', category: 'appetizers',
    ingredients: ['Crispy Pork Belly Bites', 'Tequila-Lime Glaze', 'Mango Salsa', 'Smashed Sweet Plantain', 'Melted Cheese'] },
  { id: 'nopal-wings', name: 'Nopal Wings', category: 'appetizers',
    notes: 'Specialty flavors: Nopal Diablo, Mango-Chili, Buffalo, Mexican Street Corn',
    ingredients: ['Agave Marinated Chicken Wings', 'Tequila-Lime Glaze'] },
  { id: 'crispy-riblets', name: 'Crispy Riblets', category: 'appetizers',
    ingredients: ['Slow Roasted-Flash Fried Riblets', 'Tequila-Lime Glaze', 'Pickled Housemade Jalapeños'] },
  { id: 'crispy-brussels-sprouts', name: 'Crispy Brussels Sprouts', category: 'appetizers',
    ingredients: ['Crispy Brussels Sprouts', 'House Made Chorizo', 'Queso Fundido'] },
  { id: 'avocado-eggrolls', name: 'Avocado Eggrolls', category: 'appetizers',
    ingredients: ['Roasted Peppers', 'Crushed Fresh Avocado', 'Pickled Onions', 'Chipotle Aioli', 'Salsa Verde'] },
  { id: 'nachos-nopal', name: 'Nachos Nopal', category: 'appetizers',
    ingredients: ['Crispy Corn Tortillas', 'Melted Mexican Cheese Blend', 'Guacamole', 'Refried Beans', 'Sour Cream', 'Pico de Gallo', 'Pickled Jalapeños'] },
  { id: 'queso-fundido', name: 'Queso Fundido', category: 'appetizers',
    ingredients: ['Baked Mexican Cheeses', 'Poblano Rajas Relish', 'Crispy Corn Tortillas'] },
  { id: 'chips-salsa', name: 'Chips + Salsa', category: 'appetizers',
    ingredients: ['Bottomless Housemade Fresh Salsa', 'Crispy Tortilla Chips'] },
  { id: 'chips-guacamole', name: 'Chips + Guacamole', category: 'appetizers',
    ingredients: ['Fresh Guacamole', 'Crispy Tortilla Strips'] },
  { id: 'street-corn-avocado', name: 'Mexican Street Corn Avocado', category: 'appetizers',
    ingredients: ['Grilled Avocado', 'Vegan Chipotle Mayo', 'Corz Salsa', 'Queso Fresco', 'Pickled Jalapeños', 'Tajin', 'Micro Cilantro', 'Pumpkin Seeds'] },
  { id: 'ropa-vieja-tostones', name: 'Ropa Vieja Tostones Chalupitas', category: 'appetizers',
    ingredients: ['Braised Beef', 'Peppers & Onions', 'Tomato', 'Cilantro', 'Guacamole', 'Queso Fresco', 'Guajillo Sauce'] },
  { id: 'mexican-street-corn', name: 'Mexican Street Corn', category: 'appetizers',
    ingredients: ['Corn on the Cob', 'Cilantro Crema', 'Cotija Cheese', 'Tajin'] },

  // ── TACOS ──
  { id: 'taco-camaron', name: 'Camarón Tacos', category: 'tacos',
    ingredients: ['Crispy Fried Shrimp', 'Red Chili Aioli', 'Cilantro-Cabbage Slaw', 'Mango Salsa', 'Rice', 'Beans'] },
  { id: 'taco-pork-belly', name: 'Pork Belly Tacos', category: 'tacos',
    ingredients: ['Crispy Fatty Chicharrones', 'Tequila-Lime Glaze', 'Cilantro-Cabbage Slaw', 'Mango Salsa', 'Rice', 'Beans'] },
  { id: 'taco-chorizo', name: 'Chorizo Tacos', category: 'tacos',
    ingredients: ['House Made Chorizo', 'Queso Fresco', 'Tomatillo-Avocado Salsa', 'Rice', 'Beans'] },
  { id: 'taco-barbacoa', name: 'Barbacoa Tacos', category: 'tacos',
    ingredients: ['Braised Beef', 'Tomatillo-Avocado Salsa', 'Queso Fresco', 'Rice', 'Beans'] },
  { id: 'taco-carnitas', name: 'Carnitas Tacos', category: 'tacos',
    ingredients: ['Braised Pulled Pork', 'Tomatillo-Avocado Salsa', 'Chopped Onions', 'Cilantro', 'Rice', 'Beans'] },
  { id: 'taco-birria', name: 'Birria Tacos', category: 'tacos',
    ingredients: ['Birria-Style Beef', 'Corn Tortilla', 'Mexican Cheese', 'Beef Consomé', 'Avocado-Tomatillo Sauce', 'Mexican Rice'] },
  { id: 'taco-pescado-borracho', name: 'Pescado Borracho Tacos', category: 'tacos',
    notes: 'Fish of the day',
    ingredients: ['Beer Battered Fried Fish', 'Chipotle Aioli', 'Cilantro-Cabbage Slaw', 'Pico de Gallo', 'Rice', 'Beans'] },
  { id: 'taco-carne-asada', name: 'Carne Asada Tacos', category: 'tacos',
    ingredients: ['Marinated & Grilled Steak', 'Chopped Onions', 'Cilantro', 'Radishes', 'Tomatillo-Avocado Salsa', 'Rice', 'Beans'] },
  { id: 'taco-pollo-tinga', name: 'Pollo Tinga Tacos', category: 'tacos',
    ingredients: ['Braised & Shredded Chicken', 'Crema Mexicana', 'Queso Fresco', 'Cilantro', 'Rice', 'Beans'] },
  { id: 'taco-campechanos', name: 'Campechanos Tacos', category: 'tacos',
    ingredients: ['Carne Asada', 'House Made Chorizo', 'Sautéed Peppers & Onions', 'Chopped Cilantro', 'Tomatillo-Avocado Salsa', 'Rice', 'Beans'] },
  { id: 'taco-al-pastor', name: 'Tacos Al Pastor', category: 'tacos',
    ingredients: ['Adobo Marinated Pork Tenderloin', 'Tomatillo-Avocado Sauce', 'Pineapple Salsa', 'White Rice', 'Black Beans'] },

  // ── ENCHILADAS ──
  { id: 'enchiladas-barbacoa', name: 'Barbacoa Enchiladas', category: 'enchiladas',
    ingredients: ['Braised Beef', 'Tomatillo or Guajillo Sauce', 'Mexican Blend Cheese', 'Mexican Crema', 'Queso Fresco', 'Lettuce', 'Radishes', 'Mexican Rice', 'Refried Beans'] },
  { id: 'enchiladas-carnitas', name: 'Carnitas Enchiladas', category: 'enchiladas',
    ingredients: ['Braised Pulled Pork', 'Tomatillo or Guajillo Sauce', 'Mexican Blend Cheese', 'Mexican Crema', 'Queso Fresco', 'Lettuce', 'Radishes', 'Mexican Rice', 'Refried Beans'] },
  { id: 'enchiladas-pollo', name: 'Pollo Enchiladas', category: 'enchiladas',
    ingredients: ['Chicken', 'Tomatillo or Guajillo Sauce', 'Mexican Blend Cheese', 'Mexican Crema', 'Queso Fresco', 'Lettuce', 'Radishes', 'Mexican Rice', 'Refried Beans'] },
  { id: 'enchiladas-carne-asada', name: 'Carne Asada Enchiladas', category: 'enchiladas',
    ingredients: ['Grilled Steak', 'Tomatillo or Guajillo Sauce', 'Mexican Blend Cheese', 'Mexican Crema', 'Queso Fresco', 'Lettuce', 'Radishes', 'Mexican Rice', 'Refried Beans'] },
  { id: 'enchiladas-chorizo', name: 'Chorizo Enchiladas', category: 'enchiladas',
    ingredients: ['House Made Chorizo', 'Tomatillo or Guajillo Sauce', 'Mexican Blend Cheese', 'Mexican Crema', 'Queso Fresco', 'Lettuce', 'Radishes', 'Mexican Rice', 'Refried Beans'] },
  { id: 'enchiladas-cheesy', name: 'Cheesy Enchiladas', category: 'enchiladas',
    ingredients: ['Queso Fundido', 'Queso Fresco', 'Crema Mexicana', 'Pickled Onions', 'Mexican Rice', 'Refried Beans'] },
  { id: 'enchiladas-camaron', name: 'Camarón Enchiladas', category: 'enchiladas',
    ingredients: ['Shrimp', 'Tomatillo or Guajillo Sauce', 'Mexican Blend Cheese', 'Mexican Crema', 'Queso Fresco', 'Lettuce', 'Radishes', 'Mexican Rice', 'Refried Beans'] },
  { id: 'enchiladas-vegetales', name: 'Vegetales Enchiladas', category: 'enchiladas',
    ingredients: ['Seasonal Vegetables', 'Tomatillo or Guajillo Sauce', 'Mexican Blend Cheese', 'Mexican Crema', 'Queso Fresco', 'Lettuce', 'Radishes', 'Mexican Rice', 'Refried Beans'] },

  // ── BURRITOS ──
  { id: 'burrito-barbacoa', name: 'Barbacoa Burrito', category: 'burritos',
    ingredients: ['Braised Beef', 'Refried Beans', 'Mexican Blend Cheese', 'Mexican Rice', 'Guacamole', 'Sour Cream', 'Pico de Gallo'] },
  { id: 'burrito-carnitas', name: 'Carnitas Burrito', category: 'burritos',
    ingredients: ['Braised Pulled Pork', 'Refried Beans', 'Mexican Blend Cheese', 'Mexican Rice', 'Guacamole', 'Sour Cream', 'Pico de Gallo'] },
  { id: 'burrito-grilled-chicken', name: 'Grilled Chicken Burrito', category: 'burritos',
    ingredients: ['Grilled Chicken', 'Refried Beans', 'Mexican Blend Cheese', 'Mexican Rice', 'Guacamole', 'Sour Cream', 'Pico de Gallo'] },
  { id: 'burrito-carne-asada', name: 'Carne Asada Burrito', category: 'burritos',
    ingredients: ['Marinated Grilled Steak', 'Refried Beans', 'Mexican Blend Cheese', 'Mexican Rice', 'Guacamole', 'Sour Cream', 'Pico de Gallo'] },
  { id: 'burrito-chorizo', name: 'Chorizo Burrito', category: 'burritos',
    ingredients: ['House Made Chorizo', 'Refried Beans', 'Mexican Blend Cheese', 'Mexican Rice', 'Guacamole', 'Sour Cream', 'Pico de Gallo'] },
  { id: 'burrito-camaron', name: 'Camarón Burrito', category: 'burritos',
    ingredients: ['Shrimp', 'Refried Beans', 'Mexican Blend Cheese', 'Mexican Rice', 'Guacamole', 'Sour Cream', 'Pico de Gallo'] },
  { id: 'burrito-campechano', name: 'Campechano Burrito', category: 'burritos',
    ingredients: ['Carne Asada', 'House Made Chorizo', 'Refried Beans', 'Mexican Blend Cheese', 'Mexican Rice', 'Guacamole', 'Sour Cream', 'Pico de Gallo'] },
  { id: 'burrito-pork-enchilado', name: 'Pork Enchilado Burrito', category: 'burritos',
    ingredients: ['Pork Enchilado', 'Refried Beans', 'Mexican Blend Cheese', 'Mexican Rice', 'Guacamole', 'Sour Cream', 'Pico de Gallo'] },
  { id: 'burrito-pork-belly', name: 'Pork Belly Burrito', category: 'burritos',
    ingredients: ['Crispy Pork Belly', 'Refried Beans', 'Mexican Blend Cheese', 'Mexican Rice', 'Guacamole', 'Sour Cream', 'Pico de Gallo'] },

  // ── QUESADILLAS ──
  { id: 'quesadilla-cheese', name: 'Cheese Quesadilla', category: 'quesadillas',
    ingredients: ['Mexican Blend Cheese', 'Sautéed Peppers & Onions', 'Sour Cream', 'Pico de Gallo'] },
  { id: 'quesadilla-chicken', name: 'Chicken Quesadilla', category: 'quesadillas',
    ingredients: ['Grilled Chicken', 'Mexican Blend Cheese', 'Sautéed Peppers & Onions'] },
  { id: 'quesadilla-carnitas', name: 'Carnitas Quesadilla', category: 'quesadillas',
    ingredients: ['Braised Pulled Pork (Carnitas)', 'Mexican Blend Cheese', 'Sautéed Peppers & Onions'] },
  { id: 'quesadilla-chorizo', name: 'Chorizo Quesadilla', category: 'quesadillas',
    ingredients: ['House Made Chorizo', 'Mexican Blend Cheese', 'Sautéed Peppers & Onions'] },
  { id: 'quesadilla-barbacoa', name: 'Barbacoa Quesadilla', category: 'quesadillas',
    ingredients: ['Braised Beef (Barbacoa)', 'Mexican Blend Cheese', 'Sautéed Peppers & Onions'] },
  { id: 'quesadilla-asada', name: 'Asada Quesadilla', category: 'quesadillas',
    ingredients: ['Grilled Steak (Asada)', 'Mexican Blend Cheese', 'Sautéed Peppers & Onions'] },
  { id: 'quesadilla-camaron', name: 'Camarón Quesadilla', category: 'quesadillas',
    ingredients: ['Shrimp', 'Mexican Blend Cheese', 'Sautéed Peppers & Onions'] },
  { id: 'quesadilla-hawaiian', name: 'Hawaiian Quesadilla', category: 'quesadillas',
    ingredients: ['Ham', 'Pineapple', 'Mexican Blend Cheese', 'Sautéed Peppers & Onions'] },
  { id: 'quesadilla-blackened-salmon', name: 'Blackened Salmon Quesadilla', category: 'quesadillas',
    ingredients: ['Blackened Salmon', 'Mexican Blend Cheese', 'Sautéed Peppers & Onions'] },

  // ── ENTREES (PLATOS) ──
  { id: 'salmon-veracruz', name: 'Salmon Veracruz', category: 'entrees',
    ingredients: ['Pan-Seared Salmon', 'White Steamed Rice', 'Veracruz Sauce', 'Tomato', 'Onions', 'Peppers', 'Olives', 'Capers', 'Spinach'] },
  { id: 'blackened-mahi-mahi', name: 'Blackened Mahi Mahi', category: 'entrees',
    ingredients: ['Blackened Mahi-Mahi', 'Quinoa Baby Mix', 'Tomatoes', 'Corn', 'Cilantro', 'Jalapeños', 'Prickly Pear Vinaigrette', 'Mango Salsa', 'Chili Mango Glaze'] },
  { id: 'camarones-mexicana', name: 'Camarones a la Mexicana', category: 'entrees',
    ingredients: ['Sautéed Large Shrimp', 'Peppers', 'Onions', 'Tomatoes', 'Spinach', 'Cilantro', 'White Rice'] },
  { id: 'camarones-mojo-de-ajo', name: 'Camarones al Mojo de Ajo', category: 'entrees',
    ingredients: ['Sautéed Shrimp', 'White Wine-Garlic Butter Sauce', 'White Rice', 'Sweet Plantains', 'Mixed Green Salad'] },
  { id: 'camarones-veracruz', name: 'Camarones a la Veracruz', category: 'entrees',
    ingredients: ['Sautéed Shrimp', 'White Steamed Rice', 'Veracruz Sauce', 'Tomato', 'Onions', 'Peppers', 'Olives', 'Capers'] },
  { id: 'camarones-guajillo', name: 'Camarones al Guajillo', category: 'entrees',
    ingredients: ['Shrimp', 'Garlic Guajillo Butter Sauce', 'White Rice', 'Black Beans', 'Sweet Plantains', 'Mango Salsa'] },
  { id: 'nopal-shrimp-scampi', name: 'Nopal Shrimp Scampi', category: 'entrees',
    ingredients: ['Sautéed Shrimp', 'White-Wine Creamy Chipotle Sauce', 'Fresh Tomatoes', 'Spinach', 'Linguine Pasta', 'Queso Fresco'] },
  { id: 'grilled-chicken-breasts', name: 'Grilled Chicken Breasts', category: 'entrees',
    ingredients: ['Two Grilled Chicken Breasts', 'Melted Mexican Blend Cheese', 'Sweet Plantains', 'Mexican Rice', 'Refried Beans', 'Pico de Gallo'] },
  { id: 'chicken-milanese', name: 'Chicken Milanese', category: 'entrees',
    ingredients: ['Breaded Pan-Fried Chicken Breast', 'Creamy Chorizo-Chipotle Sauce', 'Linguine Pasta', 'Parmesan'] },
  { id: 'pollo-acapulco', name: 'Pollo Acapulco', category: 'entrees',
    ingredients: ['Two Pan-Roasted Chicken Breasts', 'Mango-Chili Butter Sauce', 'White Rice', 'Garlic Spinach'] },

  // ── FAJITAS ──
  { id: 'fajita-steak', name: 'Steak Fajitas', category: 'fajitas',
    ingredients: ['Grilled Steak', 'Peppers', 'Onions', 'Nopales', 'Baby Portobello Mushrooms', 'Tomato Sauce', 'Spinach', 'Mexican Rice', 'Refried Beans', 'Guacamole', 'Sour Cream', 'Pico de Gallo'] },
  { id: 'fajita-shrimp', name: 'Shrimp Fajitas', category: 'fajitas',
    ingredients: ['Shrimp', 'Peppers', 'Onions', 'Nopales', 'Baby Portobello Mushrooms', 'Tomato Sauce', 'Spinach', 'Mexican Rice', 'Refried Beans', 'Guacamole', 'Sour Cream', 'Pico de Gallo'] },
  { id: 'fajita-chicken', name: 'Chicken Fajitas', category: 'fajitas',
    ingredients: ['Grilled Chicken', 'Peppers', 'Onions', 'Nopales', 'Baby Portobello Mushrooms', 'Tomato Sauce', 'Spinach', 'Mexican Rice', 'Refried Beans', 'Guacamole', 'Sour Cream', 'Pico de Gallo'] },
  { id: 'fajita-vegetable', name: 'Vegetable Fajitas', category: 'fajitas',
    ingredients: ['Peppers', 'Onions', 'Nopales', 'Baby Portobello Mushrooms', 'Tomato Sauce', 'Spinach', 'Mexican Rice', 'Refried Beans', 'Guacamole', 'Sour Cream', 'Pico de Gallo'] },
  { id: 'fajita-nopal', name: 'Nopal Fajita (All Three!)', category: 'fajitas',
    notes: 'Steak + Chicken + Shrimp',
    ingredients: ['Steak', 'Chicken', 'Shrimp', 'Peppers', 'Onions', 'Nopales', 'Baby Portobello Mushrooms', 'Tomato Sauce', 'Spinach', 'Mexican Rice', 'Refried Beans', 'Guacamole', 'Sour Cream', 'Pico de Gallo'] },

  // ── SALADS ──
  { id: 'taco-salad', name: 'Taco Salad', category: 'salads',
    ingredients: ['Tri-Color Greens', 'Grilled Chicken', 'Refried Beans', 'Guacamole', 'Pico de Gallo', 'Mexican Rice', 'Olive Oil', 'Prickly Pear Vinaigrette'] },
  { id: 'southwest-quinoa-salad', name: 'Southwest Quinoa Salad', category: 'salads',
    ingredients: ['Guajillo Marinated Chicken', 'Tri-Color Greens', 'Quinoa', 'Avocado', 'Peppers', 'Charred Corn', 'Chili Roasted Pepitas', 'Queso Fresco', 'Crispy Tortilla Strips', 'Olive Oil', 'Cumin-Lime Vinaigrette'] },
  { id: 'nopal-steak-house-salad', name: 'Nopal Steak House Salad', category: 'salads',
    ingredients: ['Grilled Arrachera Steak', 'Grilled Nopales', 'Red Onions', 'Tomatoes', 'Avocado', 'Queso Fresco', 'Cucumbers', 'Mixed Greens', 'Olive Oil', 'Prickly Pear Vinaigrette'] },

  // ── SANDWICHES ──
  { id: 'pork-belly-sandwich', name: 'Pork Belly Sandwich', category: 'sandwiches',
    ingredients: ['Marinated & Braised Pork Belly', 'Pickled Onions', 'Cilantro Cabbage Slaw', 'Sweet Potato Fries'] },
  { id: 'mahi-sandwich', name: 'Mahi Sandwich', category: 'sandwiches',
    ingredients: ['8oz Mahi (Blackened or Grilled)', 'Creamy Cabbage Slaw', 'Chipotle Aioli', 'Toasted Challah Bun', 'French Fries'] },
  { id: 'fajita-philly', name: 'Fajita Philly Cheesesteak', category: 'sandwiches',
    ingredients: ['Arrachera Grilled Steak', 'Cilantro Aioli', 'Baby Portobellos', 'Peppers', 'Onions', 'Pickled Jalapeños', 'Queso Fundido', 'French Fries'] },
  { id: 'chicken-sandwich', name: 'Chicken Sandwich', category: 'sandwiches',
    ingredients: ['Grilled Chicken', 'Cilantro Crema', 'Refried Beans', 'Melted Mexican Blend Cheese', 'Cuban Bread', 'Fresh Sliced Tomatoes', 'Lettuce'] },
  { id: 'sandwich-al-pastor', name: 'Sandwich Al Pastor', category: 'sandwiches',
    ingredients: ['Adobo Marinated Pork Tenderloin', 'Chipotle Aioli', 'Cabbage Slaw', 'Pickled Onions', 'Pineapple Salsa', 'Crispy Yuca Fries'] },
  { id: 'birria-grilled-cheese', name: 'Birria Grilled Cheese', category: 'sandwiches',
    ingredients: ['Adobo Marinated Braised & Pulled Beef', 'Toasted Texas Toast', 'White Mexican Cheese Blend', 'Beef Consomé', 'Chimichurri-Yuca Fries'] },
  { id: 'nopal-shrimp-po-boy', name: 'Nopal Shrimp Po Boy', category: 'sandwiches',
    ingredients: ['Crispy Fried Shrimp', 'Toasted Baguette', 'Chipotle Aioli', 'Creamy Coleslaw', 'Pickled Jalapeños', 'French Fries'] },

  // ── BRUNCH ──
  { id: 'eggs-benedict', name: 'Eggs Benedict', category: 'brunch',
    ingredients: ['Poached Eggs', 'Toasted English Muffins', 'House Made Chorizo', 'Guacamole', 'Queso Fundido', 'Pico de Gallo', 'Crispy Tater Tots'] },
  { id: 'steak-eggs-tostadas', name: 'Steak & Eggs Tostadas', category: 'brunch',
    ingredients: ['Grilled Steak', 'Two Crispy Corn Tortillas', 'Refried Beans', 'Lettuce', 'Pico de Gallo', 'Two Fried Eggs', 'Guajillo Sauce', 'Queso Fresco'] },
  { id: 'breakfast-burrito', name: 'Breakfast Burrito', category: 'brunch',
    ingredients: ['Scrambled Eggs', 'House Made Chorizo', 'Onions & Peppers', 'Mexican Cheese Blend', 'Crispy Tater Tots'] },
  { id: 'vegetable-omelette', name: 'Vegetable Omelette', category: 'brunch',
    ingredients: ['Zucchini', 'Mushrooms', 'Onions & Peppers', 'Spinach', 'Mexican Cheese Blend', 'Baby Green Salad', 'Nopales'] },
  { id: 'breakfast-quesadilla', name: 'Breakfast Quesadilla', category: 'brunch',
    ingredients: ['Scrambled Eggs', 'House Made Chorizo', 'Onions & Peppers', 'Mexican Cheese Blend', 'Crispy Flour Tortilla', 'Sour Cream'] },
  { id: 'chorizo-omelette', name: 'Chorizo Omelette', category: 'brunch',
    ingredients: ['Homemade Chorizo', 'Mexican Cheese Blend', 'Tater Tots'] },
  { id: 'tres-leche-french-toast', name: 'Tres Leche French Toast', category: 'brunch',
    ingredients: ['Thick Sliced Brioche Bread (Dipped & Griddled)', 'Chantilly Cream', 'Raspberry Sauce'] },
  { id: 'omelette-ahogado', name: 'Omelette Ahogado', category: 'brunch',
    ingredients: ['Three Egg Omelette', 'Chorizo', 'Mexican Cheese Blend', 'Tomatillo Sauce', 'Queso Fresco', 'Sliced Avocado'] },
  { id: 'birria-hash', name: 'Birria Hash', category: 'brunch',
    ingredients: ['Adobo Marinated & Braised Beef', 'Peppers', 'Onions', 'Tater Tots', 'Spinach', 'Two Eggs', 'Queso Fundido', 'Pico de Gallo'] },

  // ── VEGGIE ──
  { id: 'veggie-quesadilla', name: 'Veggie Quesadilla', category: 'veggie',
    ingredients: ['Mushrooms', 'Caramelized Onions', 'Nopales', 'Zucchini', 'Spinach', 'Roasted Peppers', 'Mexican Cheese Blend'] },
  { id: 'veggie-taco', name: 'Veggie Taco', category: 'veggie',
    ingredients: ['Mushrooms', 'Nopales', 'Peppers', 'Onions', 'Zucchini', 'Spinach', 'Vegan Chipotle Mayo', 'Crispy Pepitas', 'Radishes', 'Queso Fresco', 'White Rice', 'Refried Beans'] },
  { id: 'veggie-burrito', name: 'Veggie Burrito', category: 'veggie',
    ingredients: ['Mushrooms', 'Nopales', 'Peppers', 'Onions', 'Spinach', 'Zucchini', 'Mexican Cheese Blend', 'White Rice', 'Refried Beans', 'Guacamole', 'Pico de Gallo'] },
  { id: 'sauteed-veggie-plate', name: 'Sautéed Veggie Plate', category: 'veggie',
    ingredients: ['Sautéed Mushrooms', 'Peppers', 'Onions', 'Spinach', 'Zucchini', 'Queso Fresco', 'Olive Oil', 'Garlic', 'White Rice', 'Refried Beans with Vegan Cheese'] },
  { id: 'beyond-burger', name: 'Beyond Burger', category: 'veggie',
    ingredients: ['Veggie Patty', 'Lettuce', 'Tomato', 'Onions', 'Pickles', 'Vegan Mayo', 'Sweet Potato Fries'] },

  // ── DESSERTS ──
  { id: 'corn-creme-brulee', name: 'Corn Crème Brûlée', category: 'desserts',
    ingredients: ['Core Crème Brûlée', 'Vanilla Whipped Cream', 'Cherry'] },
  { id: 'churro-sundae', name: 'Churro Sundae', category: 'desserts',
    ingredients: ['Crispy Churros', 'Vanilla Ice Cream', 'Chocolate Sauce', 'Raspberry Sauce'] },
  { id: 'mexican-chocolate-mousse', name: 'Mexican Chocolate Mousse', category: 'desserts',
    ingredients: ['Chocolate Mousse', 'Crushed Oreo Crumbles'] },
  { id: 'house-made-choc-ice-cream', name: 'House Made Chocolate Ice Cream', category: 'desserts',
    ingredients: ['House Made Chocolate Ice Cream', 'Raspberry Sauce'] },
  { id: 'tres-leches', name: 'Tres Leches', category: 'desserts',
    ingredients: ['Tres Leches Cake', 'Chantilly Cream', 'Raspberry Coulis', 'Cherry'] },
  { id: 'vanilla-ice-cream', name: 'Vanilla Ice Cream', category: 'desserts',
    ingredients: ['Vanilla Ice Cream', 'Chocolate Sauce'] },
  { id: 'mexican-bread-pudding', name: 'Mexican Bread Pudding', category: 'desserts',
    ingredients: ['Warm Bread Pudding', 'Toasted Brioche', 'Raisins', 'Chocolate Chips', 'Queso Fresco', 'Vanilla Ice Cream'] },
  { id: 'cafe-con-leche-brulee', name: 'Café con Leche Crème Brûlée', category: 'desserts',
    ingredients: ['Café con Leche Crème Brûlée', 'Whipped Cream', 'Cherry'] },
];
